### ISSUE TITLE
Error with installation on Python 3.9

### ISSUE THREAD

**Issue by flxai** [marceloprates/prettymaps#10]
If I follow the installation instructions, `vsketch` works, but for `prettymaps` I get the following error:

```
pip install "git+https://github.com/marceloprates/prettymaps.git"
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/marceloprates/prettymaps.git
  Cloning https://github.com/marceloprates/prettymaps.git to /tmp/pip-req-build-9bvx3_4y
  Running command git clone -q https://github.com/marceloprates/prettymaps.git /tmp/pip-req-build-9bvx3_4y
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 454, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 319, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 176, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/lib/python3.9/site-packages/resolvelib/resolvers.py", line 80, in from_requirement
    cands = build_iter_view(matches)
  File "/usr/lib/python3.9/site-packages/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 285, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "/usr/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "/usr/lib/python3.9/site-packages/packaging/specifiers.py", line 790, in contains
    item = parse(item)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

This is within a [Miniconda](https://docs.conda.io/en/latest/miniconda.html) environment using Python 3.9. Is there a way to fix this?

**Comment by jmbernabotto** [comment]
Hello.
I have pip version 21.2.4, but unfortunately, I can't install vsketch.
I use Mac mini M1.
It's perhaps the reason ! 
here the message 
ERROR: Could not find a version that satisfies the requirement vsketch (unavailable) (from versions: none)
ERROR: No matching distribution found for vsketch (unavailable)

**Comment by flxai** [comment]
Thanks to both of you. The import of `prettymaps` works, but [now `vsketch` is broken](https://github.com/abey79/vsketch/issues/145). I will close the issue because it is solved.

@jmbernabotto I'd suggest opening a new issue that details the commands you used. Your issue is different from this one and its current description is not clear enough to help you. Also maybe try invoking pip using `pip3 install ...` or even `python3 -m pip install ...`.

**Comment by abey79** [comment]
@jmbernabotto Use the latest of Python 3.9 series installed with MacPort. I know of no other setup that will properly work on M1 macs.
