### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'axis'

### ISSUE THREAD

**Issue by bensnoozled** [marceloprates/prettymaps#103]
First off, thanks for such an interesting project!

I'm trying to run the examples locally. Getting the following error:
```
 plot = prettymaps.plot('Stad van de Zon, Heerhugowaard, Netherlands', radius = False)
/home/ben/.local/lib/python3.8/site-packages/osmnx/geocoder.py:110: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  gdf = gdf.append(_geocode_query_to_gdf(q, wr, by_osmid))
/home/ben/.local/lib/python3.8/site-packages/prettymaps/draw.py:109: ShapelyDeprecationWarning: Iteration over multi-part geometries is deprecated and will be removed in Shapely 2.0. Use the `geoms` property to access the constituent parts of a multi-part geometry.
  layers = dict(zip(k, v))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ben/.local/lib/python3.8/site-packages/prettymaps/draw.py", line 251, in plot
    ax.axis("off")
AttributeError: 'NoneType' object has no attribute 'axis'
```
Any idea how to resolve? Maybe it's an issue with a dependency?

**Comment by bensnoozled** [comment]
Update on this, I used the setup instructions for the Google Colaboratory Demo, and that resolved the issue.

**Comment by tuxthepenguin84** [comment]
I'm running into this issue as well but want to run locally rather than with Google Colab Demo
