### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by antoninpa** [marceloprates/prettymaps#113]
```
import prettymaps
from matplotlib import pyplot as plt

plot = prettymaps.plot(
    'Bom Fim, Porto Alegre, Brasil', radius = False,
)

plt.show()
```
This code fails and produces :

Traceback (most recent call last):
  File "/home/.../prettymaps/Madrid.py", line 5, in <module>
    plot = prettymaps.plot(
  File "/home/.../prettymaps/prettymaps/draw.py", line 951, in plot
    plot_gdf(
  File "/home/.../prettymaps/prettymaps/draw.py", line 247, in plot_gdf
    PolygonPatch(
  File "/home/.../prettymaps/prettymaps/draw.py", line 172, in PolygonPatch
    exterior = np.array(poly.exterior.xy)
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

**Comment by antoninpa** [comment]
My bad, I had to reinstall my virtual env. Sorry !

**Comment by marceloprates** [comment]
No problem, thanks!
