### ISSUE TITLE
I am beginner, i need help to execute the script

### ISSUE THREAD

**Issue by mikear** [marceloprates/prettymaps#24]
Someone can send me a manual to run the script?

The IDLE Shell show me this report:

...prettymaps-main\prettymaps-main\prueba.py
Traceback (most recent call last):
  File "C:\Users\Mike\Desktop\cruso QGIS\prettymaps-main\prettymaps-main\prueba.py", line 2, in <module>
    fig, ax = plt.subplots(figsize = (12, 12), constrained_layout = True)
NameError: name 'plt' is not defined
>>> 

Thank you!

![image](https://user-images.githubusercontent.com/21364876/131134435-c9eccd8c-d139-48e0-bd05-b892d3a4efb7.png)

**Comment by zhuang-hao-ming** [comment]
You can check this tiny [repo](https://github.com/zhuang-hao-ming/pretty_gpd) inspired by prettymaps. It contained less than 100 lines of code and is easy to follow.

**Comment by omwyman** [comment]
> Someone can send me a manual to run the script?
> 
> The IDLE Shell show me this report:
> 
> ...prettymaps-main\prettymaps-main\prueba.py
> Traceback (most recent call last):
> File "C:\Users\Mike\Desktop\cruso QGIS\prettymaps-main\prettymaps-main\prueba.py", line 2, in
> fig, ax = plt.subplots(figsize = (12, 12), constrained_layout = True)
> NameError: name 'plt' is not defined
> 
> > > >
> 
> Thank you!
> 
> ![image](https://user-images.githubusercontent.com/21364876/131134435-c9eccd8c-d139-48e0-bd05-b892d3a4efb7.png)

Have you reviewed the Google Collab Demo? I suggest following the instructions there to compile and run the examples.

Some notes:

I am running windows, and I needed to install Fiona, GDAL, and geopandas from binaries collected from Christoph Gohlke (https://www.lfd.uci.edu/~gohlke/pythonlibs/) since the installation instructions provided in the Google Collab failed. Specifically, it failed when trying to install Fiona.

When running any example, make sure to include the following imports (snipped taken from the Google Collab Demo):

import vsketch
from prettymaps import *
import matplotlib.font_manager as fm
from matplotlib import pyplot as plt


Hope this clarifies some 😄

**Comment by matthewcuyugan** [comment]
> > Someone can send me a manual to run the script?
> > The IDLE Shell show me this report:
> > ...prettymaps-main\prettymaps-main\prueba.py
> > Traceback (most recent call last):
> > File "C:\Users\Mike\Desktop\cruso QGIS\prettymaps-main\prettymaps-main\prueba.py", line 2, in
> > fig, ax = plt.subplots(figsize = (12, 12), constrained_layout = True)
> > NameError: name 'plt' is not defined
> > > > >
> > 
> > 
> > Thank you!
> > ![image](https://user-images.githubusercontent.com/21364876/131134435-c9eccd8c-d139-48e0-bd05-b892d3a4efb7.png)
> 
> Have you reviewed the Google Collab Demo? I suggest following the instructions there to compile and run the examples.
> 
> Some notes:
> 
> I am running windows, and I needed to install Fiona, GDAL, and geopandas from binaries collected from Christoph Gohlke (https://www.lfd.uci.edu/~gohlke/pythonlibs/) since the installation instructions provided in the Google Collab failed. Specifically, it failed when trying to install Fiona.
> 
> When running any example, make sure to include the following imports (snipped taken from the Google Collab Demo):
> 
> import vsketch
> from prettymaps import *
> import matplotlib.font_manager as fm
> from matplotlib import pyplot as plt
> 
> Hope this clarifies some 😄

I'm having an error while installing the geopandas. :(

![image](https://user-images.githubusercontent.com/89746755/131262533-b6ec1121-8e7c-40ed-a7e6-984268929856.png)

**Comment by omwyman** [comment]
> > > Someone can send me a manual to run the script?
> > > The IDLE Shell show me this report:
> > > ...prettymaps-main\prettymaps-main\prueba.py
> > > Traceback (most recent call last):
> > > File "C:\Users\Mike\Desktop\cruso QGIS\prettymaps-main\prettymaps-main\prueba.py", line 2, in
> > > fig, ax = plt.subplots(figsize = (12, 12), constrained_layout = True)
> > > NameError: name 'plt' is not defined
> > > > > >
> > > 
> > > 
> > > Thank you!
> > > ![image](https://user-images.githubusercontent.com/21364876/131134435-c9eccd8c-d139-48e0-bd05-b892d3a4efb7.png)
> > 
> > 
> > Have you reviewed the Google Collab Demo? I suggest following the instructions there to compile and run the examples.
> > Some notes:
> > I am running windows, and I needed to install Fiona, GDAL, and geopandas from binaries collected from Christoph Gohlke (https://www.lfd.uci.edu/~gohlke/pythonlibs/) since the installation instructions provided in the Google Collab failed. Specifically, it failed when trying to install Fiona.
> > When running any example, make sure to include the following imports (snipped taken from the Google Collab Demo):
> > import vsketch
> > from prettymaps import *
> > import matplotlib.font_manager as fm
> > from matplotlib import pyplot as plt
> > Hope this clarifies some 😄
> 
> I'm having an error while installing the geopandas. :(
> 
> ![image](https://user-images.githubusercontent.com/89746755/131262533-b6ec1121-8e7c-40ed-a7e6-984268929856.png)

I had a similar error when trying to run the library on my Windows 10 environment. Try installing it from the repository here (https://www.lfd.uci.edu/~gohlke/pythonlibs/).

Make sure to have the wheel library installed in your environment. Also, make sure to download the right version of the .whl binary from the site. It needs to match your system architecture (32/64bit) and python version. Place the .whl binary in a folder accessible in your environment, and install it via pip; i.e. `python -m pip install ../your_folder/geopandas.whl`. 

Please note that "geopandas.whl" is just a placeholder name for the bin file you should download from the link above.

Hope this helps!

**Comment by gonzalezhomar** [comment]
This solution worked for me. Before running the installation cell, I installed the GDAL and Fiona with the above comment. 

After that I ran the installation cell with 
!pip install git+https://github.com/abey79/vsketch#egg=vsketch
!pip install git+https://github.com/marceloprates/prettymaps.git

But I had trouble in the second cell with the import of shapely. So i ran pip uninstall shapely and installed it with conda install shapely. This solved some package dependencies. 

With all that, I got prettymaps working on a local enviroment.
