### ISSUE TITLE
Installation fails in WSL Ubuntu 20.04

### ISSUE THREAD

**Issue by baeric** [marceloprates/prettymaps#60]
When I try to install it, it fails with following error message:
```
pip install git+https://github.com/abey79/vsketch#egg=vsketch
Collecting vsketch from git+https://github.com/abey79/vsketch#egg=vsketch
  Cloning https://github.com/abey79/vsketch to /tmp/pip-install-qgq8p8ja/vsketch
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-qgq8p8ja/vsketch/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-qgq8p8ja/vsketch/
```

Same with the other command
Is there an alternative way to install it? It looks like something is wrong with the tmp folder, not sure what tho.

**Comment by JonFreer** [comment]
Hi,

I'm able to replicate this error but am not able to propose any solution.

Just thought I would let you know that this code does work on native Windows if that is a possible alternative for you 🙂

**Comment by matthewfeickert** [comment]
@baeric This might (?) also be resolved by Issue #15 being resolved with [`prettymaps` now on PyPI](https://pypi.org/project/prettymaps/). While I think that updating to WSL2 is a great idea in general, can you try running in your virtual environment

```console
$ python -m pip install --upgrade pip setuptools wheel
$ python -m pip install prettymaps
```
?
